"""
数据可视化报告生成模块
使用 matplotlib + seaborn 生成订阅统计图表
注意：在 256MB 以下服务器上，本模块会懒加载以节省内存
"""

import io
import logging
from typing import Optional

logger = logging.getLogger(__name__)


def _check_dependencies() -> bool:
    """检查可视化依赖是否可用"""
    try:
        import matplotlib  # noqa: F401
        import seaborn     # noqa: F401
        return True
    except ImportError:
        logger.warning("⚠️ matplotlib / seaborn 未安装，图表功能不可用。请运行: pip install matplotlib seaborn")
        return False


def generate_report_image(data: dict) -> Optional[bytes]:
    """
    根据节点解析数据生成聚合可视化长图。
    返回 PNG bytes 供 Telegram 直接发送；依赖缺失时返回 None。

    Args:
        data: 包含 'traffic' 和 'node_stats' 的解析结果字典

    Returns:
        Optional[bytes]: PNG 图片数据，或在依赖不可用时返回 None
    """
    if not _check_dependencies():
        return None

    # 在函数内部懒加载重型依赖，避免导入时就占用近 100MB 内存
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import seaborn as sns
    from utils.utils import format_traffic

    # ---- 主题设置 ----
    plt.style.use('dark_background')
    sns.set_theme(style="darkgrid", palette="deep")
    plt.rcParams.update({
        "axes.facecolor": "#121212",
        "figure.facecolor": "#121212",
        "text.color": "#E0E0E0",
        "axes.labelcolor": "#E0E0E0",
        "xtick.color": "#A0A0A0",
        "ytick.color": "#A0A0A0",
        "grid.color": "#2A2A2A",
        "grid.alpha": 0.5,
        "axes.edgecolor": "#333333",
        "font.sans-serif": ["Microsoft YaHei", "SimHei", "DejaVu Sans"],
        "axes.unicode_minus": False
    })

    traffic = data.get('traffic') or {}
    stats = data.get('node_stats') or {}
    countries = stats.get('countries', {})
    protocols = stats.get('protocols', {})

    fig = plt.figure(figsize=(10, 15))

    # ============ 1. 流量使用情况（甜甜圈图）============
    ax1 = plt.subplot(3, 1, 1)
    if traffic and traffic.get('total', 0) > 0:
        total = traffic.get('total', 1)
        used = traffic.get('used', 0)
        remaining = traffic.get('remaining', 0)

        wedges, texts, autotexts = ax1.pie(
            [used, remaining],
            labels=['已用流量', '剩余流量'],
            colors=['#FF5252', '#4CAF50'],
            autopct='%1.1f%%',
            startangle=90,
            pctdistance=0.85,
            textprops={'fontsize': 12, 'weight': 'bold'}
        )

        centre_circle = plt.Circle((0, 0), 0.70, fc='#121212')
        fig.gca().add_artist(centre_circle)

        ax1.text(
            0, 0, f"总览\n{format_traffic(total)}",
            ha='center', va='center', fontsize=16, weight='bold', color="#FFFFFF"
        )
        ax1.set_title("订阅流量使用概况", fontsize=18, pad=20, weight='bold')
    else:
        ax1.text(0.5, 0.5, "无可用流量度量数据", ha='center', va='center', fontsize=14)
        ax1.axis('off')

    # ============ 2. 国家/地区分布 Top 10（横向条形图）============
    ax2 = plt.subplot(3, 1, 2)
    if countries:
        sorted_countries = sorted(countries.items(), key=lambda x: x[1], reverse=True)[:10]
        c_names = [x[0] for x in sorted_countries]
        c_counts = [x[1] for x in sorted_countries]

        sns.barplot(x=c_counts, y=c_names, palette="viridis", ax=ax2)
        ax2.set_title("区域分布 Top 10", fontsize=16, pad=15, weight='bold')
        ax2.set_xlabel("节点数", fontsize=12)
        ax2.set_ylabel("")

        for i, v in enumerate(c_counts):
            ax2.text(v + 0.3, i, str(v), color='white', va='center', fontweight='bold')
    else:
        ax2.text(0.5, 0.5, "无可用的地理信息分布", ha='center', va='center', fontsize=14)
        ax2.axis('off')

    # ============ 3. 协议种类占比（饼图）============
    ax3 = plt.subplot(3, 1, 3)
    if protocols:
        p_names = list(protocols.keys())
        p_counts = list(protocols.values())
        colors = sns.color_palette("mako", len(p_names))

        ax3.pie(
            p_counts, labels=p_names, colors=colors,
            autopct='%1.1f%%', startangle=140,
            textprops={'fontsize': 11}
        )
        ax3.set_title("节点协议成分占比", fontsize=16, pad=15, weight='bold')
    else:
        ax3.text(0.5, 0.5, "无可用协议分类", ha='center', va='center', fontsize=14)
        ax3.axis('off')

    plt.tight_layout(pad=3.0)
    fig.text(
        0.5, 0.01,
        "Generated by Telegram Subscription Bot",
        ha='center', va='bottom', fontsize=10, color='#666666', style='italic'
    )

    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=120, bbox_inches='tight')
    plt.close(fig)

    buf.seek(0)
    return buf.getvalue()
